### ISSUE TITLE
[Bug]: `osgeo` in setup.py

### ISSUE THREAD

**Issue by cmarshak** [nasa/PROTEUS#51]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

`osgeo` is not a valid package and required in `setup.py`.

See this: https://pypi.org/project/osgeo/

Here is the error:

```
pip install osgeo 1 ↵
Collecting osgeo
  Using cached osgeo-0.0.1.tar.gz (1.2 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: osgeo
  Building wheel for osgeo (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      running bdist_wheel
      running build
      /Users/cmarshak/mambaforge/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      installing to build/bdist.macosx-11.0-arm64/wheel
      running install
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/0p/d5x2m4tx5kg1246bplsvyfyh0000gq/T/pip-install-4dkrwh7q/osgeo_664cb98142f741c7bc1d55d84a80a387/setup.py", line 32, in <module>
          setup(
        File "/Users/cmarshak/mambaforge/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/Users/cmarshak/mambaforge/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/Users/cmarshak/mambaforge/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/cmarshak/mambaforge/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/Users/cmarshak/mambaforge/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/Users/cmarshak/mambaforge/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/cmarshak/mambaforge/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 378, in run
          self.run_command("install")
        File "/Users/cmarshak/mambaforge/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/Users/cmarshak/mambaforge/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/Users/cmarshak/mambaforge/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/0p/d5x2m4tx5kg1246bplsvyfyh0000gq/T/pip-install-4dkrwh7q/osgeo_664cb98142f741c7bc1d55d84a80a387/setup.py", line 27, in run
          raise Exception(error_msg)
      Exception: In order to be able to run `from osgeo import gdal`,
      You were probably trying to install `gdal` by running `pip install osgeo`.
      Instead, you should either `pip install gdal` or replace `osgeo` with `gdal` in your requirements.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for osgeo
  Running setup.py clean for osgeo
Failed to build osgeo
Installing collected packages: osgeo
  Running setup.py install for osgeo ... error
  error: subprocess-exited-with-error

  × Running setup.py install for osgeo did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      running install
      /Users/cmarshak/mambaforge/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/0p/d5x2m4tx5kg1246bplsvyfyh0000gq/T/pip-install-4dkrwh7q/osgeo_664cb98142f741c7bc1d55d84a80a387/setup.py", line 32, in <module>
          setup(
        File "/Users/cmarshak/mambaforge/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/Users/cmarshak/mambaforge/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/Users/cmarshak/mambaforge/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/cmarshak/mambaforge/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/Users/cmarshak/mambaforge/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/Users/cmarshak/mambaforge/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/0p/d5x2m4tx5kg1246bplsvyfyh0000gq/T/pip-install-4dkrwh7q/osgeo_664cb98142f741c7bc1d55d84a80a387/setup.py", line 27, in run
          raise Exception(error_msg)
      Exception: In order to be able to run `from osgeo import gdal`,
      You were probably trying to install `gdal` by running `pip install osgeo`.
      Instead, you should either `pip install gdal` or replace `osgeo` with `gdal` in your requirements.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> osgeo

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

### What did you expect?

```
python pip install git+https://github.com/nasa/PROTEUS.git 
```

**Comment by nemo794** [comment]
Hi @cmarshak , Could you please follow the instructions in the PROTEUS README and install via `setup.py`? As noted in the README, installation via `pip` is not supported due to errors with `osgeo`. Thanks!

**Comment by cmarshak** [comment]
I see - thanks for your help. Yes, that installation works. Going to close it and let you pick it up if/when it makes sense.

For what it's worth, `osgeo` in `setup.py` (and PyPI) is a "dummy package" as noted here: https://pypi.org/project/osgeo/ (hope I am not being too much of a broken record about this). In other words, deleting this in `setup.py` would not impact dependencies and actually allow installation with pip; clearly putting `install_requires` with `gdal` is a bad idea as you really need `conda`/`mamba` for this.

**Comment by nemo794** [comment]
Thank you, @cmarshak
